### PR TITLE
Fix for 'usgovmixed' legal text, and minor typo fixes

### PR DESCRIPTION
**Pull request by dbeyer**
Needs approval by @Craig-Rodkin.

### CODE REVIEW

**Comment by Craig-Rodkin** [comment]
Hi Boris, Deb (staff) confirmed the wording is not correct. Please make the change.

Not sure where the confusion came into play

- Craig

Craig Rodkin
ACM - Publications Operations Manager
rodkin@hq.acm.org

On Jul 7, 2017 4:54 PM, Dirk Beyer <notifications@github.com> wrote:

Needs approval by @Craig-Rodkin<https://github.com/craig-rodkin>.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/borisveytsman/acmart/pull/181

Commit Summary

  *   Fix minor typo
  *   Remove text that should not appear on the paper, according to ACM RightsReview.
  *   'usgovmixed' is only for papers by U.S. government agency affiliates.
  *   Fix minor capitalization typo
  *   'usgovmixed' again: Add 'United States' to specify the government and add the 'affiliates'.

File Changes

  *   M acmart.dtx<https://github.com/borisveytsman/acmart/pull/181/files#diff-0> (16)

Patch Links:

  *   https://github.com/borisveytsman/acmart/pull/181.patch
  *   https://github.com/borisveytsman/acmart/pull/181.diff

**Comment by borisveytsman** [comment]
thanks

**Comment by Craig-Rodkin** [comment]
Boris, Going to have Deb review all rights text to ensure that the language is up-to-date and correct.

**Comment by Craig-Rodkin** [comment]
Boris, are these changes ready for download and post to the ACM webpages?

**Comment by borisveytsman** [comment]
C> Date: Mon, 10 Jul 2017 05:41:13 -0700
C> From: Craig-Rodkin <notifications@github.com>


C> Boris, are these changes ready for download and post to the ACM webpages?

Yes


-- 
Good luck

-Boris

There's no heavier burden than a great potential.

**Comment by Craig-Rodkin** [comment]
Great. The new file set is live

Regards,

-Craig

Craig Rodkin
Publications Operations Manager
Association for Computing Machinery
rodkin@hq.acm.org<mailto:rodkin@hq.acm.org>
http://member.acm.org/~rodkin

Explore Association for Computing Machinery's AUTHOR-IZER SERVICE:  http://www.acm.org/publications/acm-author-izer-service<http://www.acm.org/publications/acm-author-izer-service>

**Pull request merged**
