### PR TITLE
Initial SIGPLAN format changes

### PR DESCRIPTION
**Pull request by MatthewFluet**

### CODE REVIEW

**Comment by borisveytsman** [comment]
The rules for fullwidth captions (Table 2 and Fgure 4 in the sample) look weird.  Are you sure this is what SIGPLAN committee wants?

I would recommend using \tabularx{\columnwidth} instead of \tabular to stretch the tables.

**Comment by borisveytsman** [comment]
Or maybe get rid of the rule above table caption: it is distracting.  

Actually unneccesary rules are frown upon in fine typesetting - but this is your choice...

**Comment by krono** [comment]
I think rules over caption are only good when the caption is below the floating material, which is not the case for “good” tables. sigplanconf always had a switch to disable captionrules; maybe one could eeither provide this switch too or not have them for tables altogether.

**Comment by borisveytsman** [comment]
The purpose of a rule is to visually separate material.  I may understand a rule above and below a float (however, whitespace separation is more subtle and more preferable).  A rule between the caption and the body of a float makes too strong separation: stronger than the separation between the float and the text.  A rule above table, contrasting with table rules, is just strange

To tell the truth, I am in a difficult situation here.  SIGPLAN editors have the right for a reasonable accomodation to their tastes.  However, I am worried that these rules go too far.

**Comment by borisveytsman** [comment]
Ok, here is what I did

1.  I returned table caption for SIGPLAN on top of the float.  I strongly feel Lamport's decision here was wrong.  

2.  Accordingly I put SIGPLAN rule above the caption for figures but below the caption for tables.

3.  I added \nocaptionrule command and a couple of global commands to switch the rule on and off.

I still feel it would be much better not to use rules in captions, to tell the truth.

**Comment by MatthewFluet** [comment]
Re: "rules for fullwidth captions look weird. Are you sure this is what SIGPLAN committee wants?"  No, I don't know if this is what SIGPLAN (the community) wants.  But, I'm under the impression that ACM HQ does not have time for considered feedback, and, so, my mandate is to preserve the behavior of `sigplanconf` as much as possible.

Re: tables with captions and rules.  Again, my intention is to preserve the previous behavior, which used a rule and was intended for use with table captions below the table content.  (As a practical matter, SIGPLAN papers use tables significantly less frequently than figures and many authors will simply use a `tabular`/`array` within a `figure`.)

Re: `\nocaptionrule`  Yes, I had intended to propose such functionality to match that from `sigplanconf`.  Arguably, a failing of the implementation in `sigplanconf` (and also now in `acmart`) is that `\nocaptionrule` adjusts the vertical space of the caption and authors abuse it to save space, not for typographic reasons.

Re: "reasonable accomodation to their tastes"  There are obviously many subjective decisions in typesetting.  Without interposing my own opinions, let me simply note that `sigplanconf` was a commissioned development, much as is `acmart`.

Re: rules in figures.  While all of the example figures in `samplebody-conf` and `samplebody-journal` are images, images actually appear rather infrequently in SIGPLAN papers.  Much more common are figures with formatted source code, with EBNF descriptions, with inference rules, etc.; there the visual separation is between the text in the figure content and the text in the figure caption.

**Comment by borisveytsman** [comment]
Ok, let's hope the latest version is ok

**Pull request merged**
