### PR TITLE
Minor fixes in BibLaTeX-specific doc

### PR DESCRIPTION
**Pull request by k4rtik**

### CODE REVIEW

**Comment by k4rtik** [comment]
Hi @borisveytsman, this PR seems like it was missed. I was waiting until a new version was released to ping (v1.85 is out now).

**Comment by k4rtik** [comment]
Hi @rdicosmo, it seems like when I follow the instructions given, I get this error:
```
! Package biblatex Error: Incompatible package 'natbib'.

l.204 \blx@packageincompatibility
! Emergency stop.
 ...
l.204 \blx@packageincompatibility
!  ==> Fatal error occurred, no output PDF file produced!
```

Were you able to test the instructions outside the development repo?

**Comment by k4rtik** [comment]
I needed to pass `natbib=false` to the document class. I also had to remove `\citestyle{acmauthoryear}`.

I think these should be documented.

**Comment by rdicosmo** [comment]
Thanks @k4rtik for spotting this... Proposed fix is in PR #470

**Comment by rdicosmo** [comment]
@borisveytsman it would be great merging this PR too: it fixes typos in the documentation that we definitely want to get rid of :-)

Thanks!

**Comment by borisveytsman** [comment]
thanks

**Pull request merged**
