### PR TITLE
Add PACM:PL journal option

### PR DESCRIPTION
**Pull request by MatthewFluet**

### CODE REVIEW

**Comment by borisveytsman** [comment]
Thanks!

**Comment by Craig-Rodkin** [comment]
Hi Matthew and Boris, 
HQ staff will work on adding the PACM titles to the .cls file after the official title has been approved and registered for an ISSN number. Staff is currently working on 2 titles (IMWUT and METRICS); we are still waiting on the official title and masthead materials for the PLAN journal before we can register this one with the ISSN agency. 

Once we have the required information, we will pass them along to Boris to include in the .cls file.  

Feel free to contact me if you have any questions. Regards, Craig

**Comment by Craig-Rodkin** [comment]
Hi Matthew and Boris, Bernie just informed me that the following title was approved: "PACM on Programming Languages". He and Laura will be taking the lead in gathering the necessary required data for the ISSN registration. I'll work closely with them to get all PACM titles added to the .cls as  soon as the ISSN numbers are available.

**Comment by MatthewFluet** [comment]
@Craig-Rodkin I'm trying to prepare a suitable author template for the program chairs of ICFP'17 and OOPSLA'17 (which are scheduled to be the first two PACM PL issues).  I think it appropriate to support `\acmJournal{PACMPL}` (rather than needing to choose some other journal), even if the ISSN isn't yet available.  (In fact, a number of the journal options in `acmart.cls` do not define `\@permissionCodeOne`.)

**Comment by Craig-Rodkin** [comment]
Matthew, I do not want you to spend too much effort into temporary changes. The ISSN registration process only takes a few weeks and we have already started the registration process for the IMWUT (formerly UBICOMP) PACM title. Laura and Bernie are in the middle of gathering the necessary data and cover image file for PL and METRICS. We will start the ISSN registration process for PL early next week. Is it possible for you to hold off for a few weeks so that Boris can put in at least 2 of the titles into the .cls file?

**Comment by MatthewFluet** [comment]
@Craig-Rodkin Adding a new journal to `acmart.cls` is simply adding 7 lines, which includes documenting the new journal and setting its ISSN.  Adding PACM PL's ISSN will simply be adding a single line.

**Comment by Craig-Rodkin** [comment]
I'm worried and have always been worried about being out of synch if changes are being made in multiple places, weeks apart. If you both feel positive that this can be managed without causing any versioning problems, go for it.

Please keep me in the loop. Thanks

- Craig

Craig Rodkin
ACM - Publications Operations Manager


Matthew Fluet <notifications@github.com> wrote:


@Craig-Rodkin<https://github.com/Craig-Rodkin> Adding a new journal to acmart.cls is simply adding 7 lines, which includes documenting the new journal and setting its ISSN. Adding PACM PL's ISSN will simply be adding a single line.

-

**Comment by MatthewFluet** [comment]
@Craig-Rodkin Well, I didn't think that there were "multiple places" where `acmart.cls` was being maintained.  I thought that this was the one place.

**Comment by Craig-Rodkin** [comment]
Besides GitHub, the files live on the new platform Aptara is developing for acm and the input organizers have been testing for over a week now. Since it is on a public space, we've had authors request to use it already for submissions as well.

- Craig

Craig Rodkin
ACM - Publications Operations Manager


Matthew Fluet <notifications@github.com> wrote:


@Craig-Rodkin<https://github.com/Craig-Rodkin> Well, I didn't think that there were "multiple places" where acmart.cls was being maintained. I thought that this was the one place.

-

**Comment by MatthewFluet** [comment]
@Craig-Rodkin Sure, obviously there will be copies of `acmart.cls` at various use sites (CTAN, ACM's backend platform, users preparing their papers, etc.); one cannot use a GitHub url with `\documentclass` in a `.tex` file.  But, there should be one canonical place where changes are integrated; and I thought that this repository was that one canonical place (especially if Boris is the maintainer).  I would caution against Aptara making significant changes to `acmart.cls` itself; that is derived from `acmart.dtx` (incorporating both the class file and the documentation) and it will be significantly harder to port a patch of `acmart.cls` to a patch of `acmart.dtx`.

Of course, this may just be a confusion of workflow.  If ACM HQ is simply sending requested changes to Boris, then I believe that he is incorporating such changes into this repository.  So there is no concern about divergence.

**Comment by Craig-Rodkin** [comment]
It is ACM’s goal that Boris needs to be the single point of contact for all changes and that all changes need to be directed through a central location (ACM HQ).

Aptara are not making any changes to the template, but using it to integrate with various parts of the platform. The IMWUT organizers are using the existing (ACM Large) template as a testbed and are waiting on the title/ISSN add and Word template before releasing them to authors.


>> Of course, this may just be a confusion of workflow. If ACM HQ is simply sending requested changes to Boris, then I believe that he is incorporating such changes into this repository. So there is no concern about divergence.
Yes, we would like any and all changes sent to Boris to go through staff.

Regards,

-Craig

Craig Rodkin
Publications Operations Manager
Association for Computing Machinery
rodkin@hq.acm.org<mailto:rodkin@hq.acm.org>
http://member.acm.org/~rodkin

Explore Association for Computing Machinery's AUTHOR-IZER SERVICE:  http://www.acm.org/publications/acm-author-izer-service<http://www.acm.org/publications/acm-author-izer-service>

**Pull request merged**
